// src/routes/billing.js
const router = require('express').Router();
const pool   = require('../db/pool');
const { verifyToken, requirePlatformAdmin } = require('../middleware/auth');

router.get('/', requirePlatformAdmin, async (req, res) => {
  const { companyId } = req.query;
  try {
    let q = 'SELECT b.*, c.name as company_name FROM billing_invoices b JOIN companies c ON c.id=b.company_id';
    const p = [];
    if (companyId) { p.push(companyId); q += ' WHERE b.company_id=$1'; }
    q += ' ORDER BY b.created_at DESC';
    const { rows } = await pool.query(q, p);
    res.json(rows);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

router.post('/', requirePlatformAdmin, async (req, res) => {
  const inv = req.body;
  try {
    const { rows } = await pool.query(
      `INSERT INTO billing_invoices
        (id,company_id,invoice_no,date,due_date,status,period,subtotal,tax,total,items,auto_generated)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
       ON CONFLICT (id) DO UPDATE SET status=EXCLUDED.status, paid_on=EXCLUDED.paid_on, receipt_no=EXCLUDED.receipt_no, updated_at=NOW()
       RETURNING *`,
      [inv.id||inv.invoiceNo, inv.companyId||inv.company_id, inv.invoiceNo||inv.invoice_no,
       inv.date||new Date().toISOString().slice(0,10), inv.dueDate||inv.due_date,
       inv.status||'Unpaid', inv.period, inv.subtotal, inv.tax, inv.total,
       JSON.stringify(inv.items||[]), inv.autoGenerated||inv.auto_generated||false]);
    res.json(rows[0]);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

router.put('/:id/pay', requirePlatformAdmin, async (req, res) => {
  const { receiptNo } = req.body;
  try {
    const { rows } = await pool.query(
      `UPDATE billing_invoices SET status='Paid', paid_on=CURRENT_DATE, receipt_no=$2 WHERE id=$1 RETURNING *`,
      [req.params.id, receiptNo||`RCP-${Date.now()}`]);
    res.json(rows[0]);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

// Auto-billing: generate invoices for all active companies
router.post('/auto-run', requirePlatformAdmin, async (req, res) => {
  const { month } = req.body; // e.g. "2026-01"
  const monthKey = month || new Date().toISOString().slice(0,7);
  try {
    const { rows: companies } = await pool.query(
      `SELECT c.*, l.tier, l.status as lic_status, t.price, t.label as tier_label
       FROM companies c
       JOIN licenses l ON l.company_id=c.id
       JOIN license_tiers t ON t.id=l.tier
       WHERE l.status='Active' AND t.price>0`);
    let generated = 0;
    for (const co of companies) {
      const period = `Monthly — ${monthKey}`;
      const exists = await pool.query(
        "SELECT id FROM billing_invoices WHERE company_id=$1 AND period=$2 AND status!='Cancelled'",
        [co.id, period]);
      if (exists.rows.length) continue;
      const subtotal = parseFloat(co.price);
      const tax      = parseFloat((subtotal * 0.08).toFixed(2));
      const total    = parseFloat((subtotal + tax).toFixed(2));
      const dueDate  = new Date(); dueDate.setDate(dueDate.getDate() + 14);
      await pool.query(
        `INSERT INTO billing_invoices (id,company_id,invoice_no,date,due_date,status,period,subtotal,tax,total,items,auto_generated)
         VALUES ($1,$2,$3,$4,$5,'Unpaid',$6,$7,$8,$9,$10,true)`,
        [`INV-${monthKey.replace('-','')}-${Date.now().toString().slice(-4)}`,
         co.id, `INV-${monthKey.replace('-','')}`,
         new Date().toISOString().slice(0,10), dueDate.toISOString().slice(0,10),
         period, subtotal, tax, total,
         JSON.stringify([{desc:`${co.tier_label} License — ${co.name}`,qty:1,unit:subtotal,total:subtotal}])]);
      generated++;
    }
    res.json({ generated, month: monthKey });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

module.exports = router;
